[package]
name = "mlir-printf-dialect"
version = "0.1.0"
edition = "2024"

[dependencies]
melior = "0.24"
mlir-sys = "0.5.0"

[lib]
name = "printf_dialect"
path = "src/lib.rs"

[dev-dependencies]
libc = "0.2"
tempfile = "3"
